// @ts-check
import { URL } from 'node:url';
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import svelte from '@astrojs/svelte';
import expressiveCode from 'astro-expressive-code';
import { isSearchEngineIndexable } from './src/search-engine-index.ts';
import { siteUrl } from './src/site.ts';

// named keyword families only -- keyword.operator stays ink
const keywordScopes = [
	'keyword.control',
	'keyword.function',
	'keyword.package',
	'keyword.import',
	'keyword.type',
	'keyword.var',
	'keyword.const',
	'keyword.struct',
	'keyword.interface',
	'keyword.map',
	'keyword.channel',
	'keyword.other',
	'storage',
	'constant.language',
];

// https://astro.build/config
export default defineConfig({
	site: siteUrl,
	redirects: {
		'/errors/': '/boards/troubleshooting/',
		'/reference/': '/boards/reference/',
		'/concepts/api-shape/': '/reference/client/',
		'/concepts/architecture/': '/concepts/streams-and-messages/',
		'/concepts/consumer-group-config/': '/reference/consumer-registration/#consumerconfig',
		'/concepts/consumer-groups-and-delivery/': '/concepts/consumer-groups/',
		'/concepts/fan-out/': '/concepts/consumer-groups/',
		'/concepts/handler-outcomes/': '/reference/consume/#message-results',
		'/concepts/lifecycle/': '/concepts/retries-and-failed-messages/',
		'/concepts/message-key/': '/reference/produce/#produceoptions',
		'/concepts/queue-and-log/': '/why-sqlstreams/',
		'/concepts/routing/': '/reference/consumer-registration/#consumerconfig',
		'/guides/consumer-timeouts/': '/concepts/consumer-leases/',
		'/guides/consumer-tuning/': '/guides/size-a-consumer-queue/',
		'/guides/dead-letters/': '/troubleshooting/messages-dead-lettered/',
		'/guides/new-group-start/': '/reference/consumer-registration/#cursorposition',
		'/guides/ordered-delivery/': '/concepts/ordering/',
		'/guides/replay/': '/reference/consumer-registration/#cursorposition',
		'/guides/schedules/': '/reference/schedule-registration/',
		'/guides/schema-versions/': '/reference/message-payload/',
		'/reference/alerts/': '/reference/read-alerts/',
		'/reference/consumer/': '/reference/consumer-group/',
		'/reference/key/': '/reference/key-messages/',
		'/reference/message-options/': '/reference/consumer-registration/#messageoptions',
		'/reference/metrics/': '/reference/read-metrics/',
		'/reference/producer/': '/reference/producer-registration/',
		'/reference/scheduler/': '/reference/schedule-object/',
		'/reference/stream/': '/reference/stream-object/',
		'/reference/system/': '/reference/system-object/',
		'/errors/SQL0001/': '/reference/consume/#errors',
		'/errors/SQL0002/': '/reference/lifecycle-context/',
		'/errors/SQL0003/': '/troubleshooting/lease-repeatedly-reclaimed/',
		'/errors/SQL0004/': '/reference/stream-registration/#errors',
		'/errors/SQL0005/': '/reference/consumer-registration/#errors',
		'/errors/SQL0006/': '/reference/destroy-stream/#errors',
		'/errors/SQL0007/': '/reference/rename-stream/#errors',
		'/errors/SQL0008/': '/reference/client/#clientconfig',
		'/errors/SQL0009/': '/reference/stream-registration/#errors',
		'/errors/SQL0010/': '/reference/destroy-system/#errors',
		'/errors/SQL0011/': '/reference/destroy-system/#errors',
		'/errors/SQL0012/': '/reference/worker-logs/#ownership-and-suspension',
		'/errors/SQL0013/': '/reference/run-schedule/#errors',
		'/errors/SQL0014/': '/reference/destroy-consumer/#errors',
		'/errors/SQL0015/': '/reference/destroy-consumer/#errors',
		'/errors/SQL0016/': '/reference/destroy-consumer/#errors',
		'/errors/SQL0017/': '/reference/get-system/#returns',
		'/errors/SQL0018/': '/reference/producer-logs/#partition-not-created-ahead-sql0033',
		'/errors/SQL0019/': '/troubleshooting/commit-confirmation-lost/',
		'/errors/SQL0020/': '/reference/destroy-stream/#errors',
		'/errors/SQL0021/': '/reference/stream-registration/#errors',
		'/errors/SQL0022/': '/troubleshooting/schema-version-mismatch/',
		'/errors/SQL0023/': '/troubleshooting/schema-version-mismatch/',
		'/errors/SQL0024/': '/reference/consumer-registration/#errors',
		'/errors/SQL0025/': '/reference/schedule-registration/#errors',
		'/errors/SQL0026/': '/troubleshooting/lease-repeatedly-reclaimed/',
		'/errors/SQL0027/': '/troubleshooting/lease-repeatedly-reclaimed/',
		'/errors/SQL0028/': '/troubleshooting/messages-dead-lettered/',
		'/errors/SQL0029/': '/troubleshooting/messages-dead-lettered/',
		'/errors/SQL0030/': '/troubleshooting/messages-dead-lettered/',
		'/errors/SQL0031/': '/troubleshooting/messages-dead-lettered/',
		'/errors/SQL0032/': '/reference/consumer-logs/#configuration',
		'/errors/SQL0033/': '/reference/producer-logs/#partition-not-created-ahead-sql0033',
		'/errors/SQL0034/': '/reference/worker-logs/#ownership-and-suspension',
		'/errors/SQL0035/': '/reference/worker-logs/#ownership-and-suspension',
		'/errors/SQL0036/': '/reference/worker-logs/#tick-failures-and-duration',
		'/errors/SQL0037/': '/reference/system-logs/#scheduling',
		'/errors/SQL0038/': '/troubleshooting/produce-is-slow/',
		'/errors/SQL0039/': '/troubleshooting/consumer-handler-exceeds-timeout/',
		'/errors/SQL0040/': '/reference/worker-logs/#tick-failures-and-duration',
		'/errors/SQL0041/': '/reference/consumer-stopped-log/',
		'/errors/SQL0042/': '/reference/consumer-metrics/#consumer-session-counters',
		'/errors/SQL0043/': '/reference/consumer-metrics/#consumer-session-counters',
		'/errors/SQL0044/': '/reference/consumer-metrics/#consumer-session-counters',
		'/errors/SQL0045/': '/reference/consumer-metrics/#consumer-session-counters',
		'/errors/SQL0046/': '/reference/consumer-metrics/#consumer-session-counters',
		'/errors/SQL0047/': '/reference/consumer-metrics/#consumer-session-counters',
		'/errors/SQL0048/': '/reference/consumer-metrics/#consumer-session-counters',
		'/errors/SQL0049/': '/reference/consumer-metrics/#consumer-session-counters',
		'/errors/SQL0050/': '/reference/consumer-metrics/#consumer-session-counters',
		'/errors/SQL0051/': '/reference/consumer-metrics/#consumer-session-counters',
		'/errors/SQL0052/': '/reference/system-logs/#metrics',
		'/errors/SQL0053/': '/troubleshooting/migration-lock-timeout/',
		'/errors/SQL0054/': '/reference/consume/#message-results',
		'/errors/SQL0055/': '/reference/consume/#message-results',
		'/errors/SQL0056/': '/troubleshooting/produce-is-slow/',
		'/errors/SQL0057/': '/reference/producer-logs/#partition-created-during-insert-sql0057',
		'/errors/SQL0058/': '/reference/system-logs/#scheduling',
		'/errors/SQL0059/': '/reference/worker-logs/#configuration-replacement-sql0059',
		'/errors/SQL0060/': '/reference/consumer-logs/#configuration',
		'/errors/SQL0061/': '/reference/system-logs/#registration-changes',
		'/errors/SQL0062/': '/reference/system-logs/#registration-changes',
		'/errors/SQL0063/': '/reference/system-logs/#alerts',
		'/errors/SQL0064/': '/reference/system-registration/#errors',
		'/errors/SQL0065/': '/reference/system-logs/#system-manager',
		'/errors/SQL0066/': '/reference/compaction-head/#returns',
		'/errors/SQL0067/': '/reference/system-metrics/#worker-series',
		'/errors/SQL0068/': '/reference/system-metrics/#worker-series',
		'/errors/SQL0069/': '/reference/system-metrics/#worker-series',
		'/errors/SQL0070/': '/reference/system-metrics/#schedule-series',
		'/errors/SQL0071/': '/reference/system-metrics/#schedule-series',
		'/errors/SQL0072/': '/reference/system-metrics/#schedule-series',
		'/errors/SQL0073/': '/reference/system-metrics/#alert-series',
		'/errors/SQL0074/': '/reference/system-metrics/#alert-series',
		'/errors/SQL0075/': '/reference/system-metrics/#alert-series',
		'/errors/SQL0076/': '/reference/system-metrics/#alert-series',
		'/errors/SQL0077/': '/reference/system-metrics/#alert-series',
		'/errors/SQL0078/': '/reference/system-metrics/#alert-series',
		'/errors/SQL0079/': '/reference/stream-metrics/#collected-series',
		'/errors/SQL0080/': '/reference/consumer-metrics/#collected-group-series',
		'/errors/SQL0081/': '/reference/consumer-metrics/#collected-group-series',
		'/errors/SQL0082/': '/reference/consumer-metrics/#collected-group-series',
		'/errors/SQL0083/': '/reference/consumer-cursor-backlog/',
		'/errors/SQL0084/': '/reference/consumer-metrics/#collected-group-series',
		'/errors/SQL0085/': '/reference/consumer-metrics/#collected-group-series',
		'/errors/SQL0086/': '/reference/consumer-metrics/#collected-group-series',
		'/errors/SQL0087/': '/reference/consumer-metrics/#collected-group-series',
		'/errors/SQL0088/': '/reference/consumer-metrics/#collected-group-series',
		'/errors/SQL0089/': '/reference/consumer-metrics/#collected-group-series',
		'/errors/SQL0090/': '/reference/consumer-metrics/#collected-group-series',
		'/errors/SQL0091/': '/reference/consumer-metrics/#collected-group-series',
		'/errors/SQL0092/': '/reference/consumer-metrics/#collected-group-series',
		'/errors/SQL0093/': '/reference/consumer-metrics/#collected-group-series',
		'/errors/SQL0094/': '/reference/partition-count-alert/',
		'/errors/SQL0095/': '/reference/compaction-read-cost-alert/',
		'/errors/SQL0096/': '/reference/worker-liveness-alert/',
		'/errors/SQL0097/': '/reference/produce/#errors',
		'/errors/SQL0098/': '/reference/stream-metrics/#collected-series',
		'/errors/SQL0099/': '/reference/stream-metrics/#collected-series',
		'/errors/SQL0100/': '/reference/system-metrics/#collector-completion',
		'/errors/SQL0101/': '/reference/metric-collector-progress-alert/',
		'/errors/SQL0102/': '/reference/metrics-exporter/#export-health',
		'/errors/SQL0103/': '/reference/metrics-exporter/#export-health',
		'/errors/SQL0104/': '/reference/metrics-exporter/#rejected-families',
		'/errors/SQL0105/': '/troubleshooting/queued-message-cannot-start/',
		'/errors/SQL0106/': '/reference/maintenance/#errors',
		'/errors/SQL0107/': '/troubleshooting/worker-not-running/',
		'/errors/SQL0108/': '/troubleshooting/messages-not-claimed/',
		'/errors/SQL0109/': '/reference/system-logs/#alerts',
	},
	vite: {
		build: {
			// Vite 8's baseline-widely-available list, pinned -- the default
			// floats per Vite major, so the floor moves only by deliberate edit
			target: ['chrome111', 'edge111', 'firefox114', 'safari16.4', 'ios16.4'],
		},
		// PGlite locates its wasm assets itself; pre-bundling breaks the paths
		optimizeDeps: { exclude: ['@electric-sql/pglite'] },
	},
	integrations: [
		expressiveCode({
			themes: [
				{
					name: 'classic',
					type: 'light',
					// console-sql-pale, ink
					colors: {
						'editor.background': '#f6f9fb',
						'editor.foreground': '#22303c',
					},
					settings: [
						{ settings: { foreground: '#22303c' } },
						// band-blue-end
						{ scope: keywordScopes, settings: { foreground: '#184e7c', fontStyle: 'bold' } },
						// sticky-label-red
						{ scope: ['string'], settings: { foreground: '#b03a2e' } },
						// ink-faint
						{ scope: ['comment'], settings: { foreground: '#7c8b98', fontStyle: 'italic' } },
					],
				},
				{
					name: 'night',
					type: 'dark',
					// console-sql-pitch, ink-silver
					colors: {
						'editor.background': '#12161b',
						'editor.foreground': '#c8ccd2',
					},
					settings: [
						{ settings: { foreground: '#c8ccd2' } },
						// console-keyword-sky
						{ scope: keywordScopes, settings: { foreground: '#7fb3dd', fontStyle: 'bold' } },
						// sticky-label-coral
						{ scope: ['string'], settings: { foreground: '#e0685a' } },
						// ink-silver-faint
						{ scope: ['comment'], settings: { foreground: '#6b7178', fontStyle: 'italic' } },
					],
				},
			],
			themeCssSelector: (theme) => `[data-board-style='${theme.name}']`,
			useDarkModeMediaQuery: false,
			minSyntaxHighlightingColorContrast: 0,
			defaultProps: { frame: 'none' },
			frames: {
				extractFileNameFromCode: false,
				removeCommentsWhenCopyingTerminalFrames: false,
			},
			styleOverrides: {
				borderColor: 'var(--border-row)',
				borderRadius: '0',
				borderWidth: 'var(--space-1)',
				codeFontFamily: 'var(--font-database)',
				codeFontSize: 'var(--font-size-code)',
				codePaddingBlock: 'var(--space-13)',
				codePaddingInline: 'var(--space-16)',
				uiFontFamily: 'var(--font-chrome)',
				frames: { shadowColor: 'transparent' },
			},
		}),
		svelte(),
		mdx(),
		sitemap({
			filter: (/** @type {string} */ page) => isSearchEngineIndexable(new URL(page).pathname),
		}),
	],
});
